from typing import Dict, Any
import sys
from pathlib import Path

# Add project root to path for imports
sys.path.append(str(Path(__file__).parent.parent.parent))
from src.tools.search import execute_web_search, execute_arxiv_search

def retrieval_agent(state: Dict[str, Any]) -> dict:
    """
    Retrieval Agent: 
    Checks the state flags generated by the Planner.
    Executes appropriate search tools (Web/Wikipedia, ArXiv) and returns the retrieved documents.
    """
    query = state.get("query", "")
    needs_web = state.get("needs_web", False)
    # If not explicitly web, maybe fallback to academic (arxiv) or both if generic
    
    retrieved_documents = []
    execution_msg = []
    
    print(f"[Retrieval Agent] Executing retrieval for: '{query}'")
    
    # Simple logic: if needs_web, do wikipedia. Else do ArXiv for academic.
    # We could do both depending on intent.
    if needs_web:
        print("[Retrieval Agent] -> Triggering Web/Wiki Search")
        docs = execute_web_search(query)
        retrieved_documents.extend(docs)
        execution_msg.append("[Retrieval] Executed web search.")
    else:
        print("[Retrieval Agent] -> Triggering Academic ArXiv Search")
        docs = execute_arxiv_search(query)
        retrieved_documents.extend(docs)
        execution_msg.append("[Retrieval] Executed arxiv search.")
        
    return {
        "retrieved_documents": retrieved_documents,
        "execution_history": execution_msg
    }
